Rooted_IQtree_Mafft
---
title: "Rooted_IQtree_Mafft"
output: html_document
date: "2024-04-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(ape)
```
**Reading treefiles from iqtree and mafft analysis and rooting the tree**

```{r}
# Load necessary packages
# install.packages("ape")
library(ape)

# Read the tree file
tree_file <- "/Users/robertoregalado/Desktop/final-project-repository/Data/xylaria_maaft2_aligned.fasta.contree"
tree <- read.tree(tree_file)

# Plot the tree and root the tree
rooted_tree <- root(tree, outgroup = "NR_159859.1_Neurospora_cratophora_outgroup", resolve.root = TRUE)
#checking to see if the tree is rooted
is.rooted(rooted_tree)

plot(rooted_tree, main = "Rooted tree using mafft and iqtree2", cex = 0.8)
# Add annotation for bootstrap values
text(x = max(par()$usr[1:2]), y = mean(par()$usr[3:4]), "BSV = bootstrap values", adj = c(0.95, 0.5))

```
```
<!-- new_tip_labels <- c("NR_159859.1_Neurospora_cratophora", "MN219591.1_Xylaria_corniformis", "MG098261.1_Xylaria_longipes_strain_NW-FVA2228", "KP133498.1_Xylaria_scruposa_isolate_866", "AF163036.1_Xylaria_hypoxylon", "JX256828.1_Xylaria_schweinitzii", "MT661488.1_Xylaria_polymorpha_strain_DSM_105756", "MG098262.1_Xylaria_polymorpha_strain_NW-FVA2229", "MW447065.1_Xylaria_polymorpha_strain_FeC105", "MN846336.1_Xylaria_polymorpha_isolate_TW07032019_02", "MK595684.1_Xylaria_sp._isolate_MBD_3013") -->


